### PR TITLE
debian build

### PR DESCRIPTION
**Pull request by esetnik**

### CODE REVIEW

**Comment by esetnik** [comment]
I took a stab at it, see https://github.com/ngineered/nginx-php-fpm/pull/161

**Comment by richarvey** [comment]
We need to work out a method of keep changes in track, for example there are now more ENV's in the main Dockerfile and tweaks to the install. There are also alpine specific fixes (libiconv for example) before merging we need to have a plan for handling this kind of thing.

**Comment by esetnik** [comment]
I totally agree. One option I've seen elsewhere is to use something like https://github.com/resin-io/dockerfile-template to create one master `Dockerfile.template` which supports both `alpine` and `debian` variants. This would potentially address the specific concern of keeping ENVs consistent as well as conditionally including tweaks that are only applicable to specific variants.

**Comment by richarvey** [comment]
I'm looking at the templating now.

**Comment by gateway** [comment]
Any potential to merg this as an option?

**Pull request closed without merging**
